name: release
on:
  push: 
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  relese:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.x
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.12.1
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: sss
        run: rustup target add x86_64-pc-windows-msvc
      - name: pnpm install
        run: pnpm install
      - name: tauri dev
        run: pnpm tauri dev
      - name: tauri build
        run: pnpm tauri build
